name: tex-fmt
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install tex-fmt
        run: cargo install tex-fmt --force

      - name: Run format check
        run: make fmt-check