name: tex-fmt
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: cargo-bins/cargo-binstall@main

      - name: Install tex-fmt
        run: cargo binstall tex-fmt --no-confirm --locked
        
      - name: Run format check
        run: make fmt-check