name: tex-fmt
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install tex-fmt
        run: cargo install tex-fmt --locked --force

      - name: Run format check
        run: make fmt-check